drop table if exists SENTENCE;

CREATE TABLE SENTENCE(
    ID SERIAL PRIMARY KEY,
    SENTENCE_ID BIGINT NOT NULL,
    CRN VARCHAR NOT NULL,
    START_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    EXPECTED_END_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    TERMINATED_DATE TIMESTAMP WITH TIME ZONE,
    SENTENCE_TYPE_CODE VARCHAR NOT NULL
);