drop table if exists WORKLOAD_CALCULATION;

CREATE TABLE WORKLOAD_CALCULATION(
   CALCULATION_ID           SERIAL PRIMARY KEY,
   CALCULATED_DATE          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc', now()),
   WEEKLY_HOURS             NUMERIC(38,6) NOT NULL,
   REDUCTIONS               NUMERIC(38,6) NOT NULL,
   AVAILABLE_POINTS         BIGINT NOT NULL,
   WORKLOAD_POINTS          BIGINT NOT NULL,
   STAFF_CODE               VARCHAR NOT NULL,
   TEAM_CODE                VARCHAR NOT NULL,
   PROVIDER_CODE            VARCHAR NOT NULL,
   BREAKDOWN_DATA           JSONB NULL
);