ALTER TABLE SENTENCE DROP CONSTRAINT SENTENCE_pkey;
ALTER TABLE SENTENCE ADD PRIMARY KEY (SENTENCE_ID);
ALTER TABLE SENTENCE DROP COLUMN ID;
DELETE FROM sentence
    WHERE TERMINATED_DATE IS NOT NULL;
ALTER TABLE SENTENCE DROP COLUMN TERMINATED_DATE;