ALTER TABLE EVENT_MANAGER_AUDIT ADD COLUMN SPO_OVERSIGHT_NOTES VARCHAR NULL;
ALTER TABLE EVENT_MANAGER_AUDIT ADD COLUMN SENSITIVE_OVERSIGHT_NOTES BOOLEAN NULL;
ALTER TABLE EVENT_MANAGER_AUDIT ALTER COLUMN ALLOCATION_JUSTIFICATION_NOTES DROP NOT NULL;
ALTER TABLE EVENT_MANAGER_AUDIT ALTER COLUMN SENSITIVE_NOTES DROP NOT NULL;